CXXFLAGS  += -I/Users/axd985/Dropbox/Documents/amuse/src/amuse/community/seba/src/SeBa/include -I/Users/axd985/Dropbox/Documents/amuse/src/amuse/community/seba/src/SeBa/include/star -DHAVE_CONFIG_H
CFLAGS    +=	-O

CXXFLAGS += -D_SRC_='"no_source_available"'